### ISSUE TITLE
Unable to disable automatic signals 

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/KotlinSDK#6]
A customer found that even passing an empty list as providers causes unwanted signals to be sent to TelemetryDeck. 

![Screenshot](https://user-images.githubusercontent.com/954120/161426430-6e1e4647-6113-404a-8fa9-5ad4e20c0094.jpg)

**Comment by kkostov** [comment]
@winsmith is it known which type of signals are causing the problem?

In the screenshot we see that an instance of `SessionProvider` is added to the list. By default, the  `NewSessionBegan` signals will be sent automatically by SessionProvider. If this is not desired, the `SessionProvider` can be skipped e.g.:

```kotlin
val providers = listOf(EnvironmentMetadataProvider())
val builder = TelemetryManager.Builder()
  .appID("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
  .showDebugLogs(true)
  .providers(providers)

TelemetryManager.start(application, builder)
```

To also disable enrichment of signals, one can also pass a completely empty list:

```kotlin
val builder = TelemetryManager.Builder()
  .appID("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
  .showDebugLogs(true)
  .providers(emptyList())

TelemetryManager.start(application, builder)
```

**Comment by winsmith** [comment]
The problem was with the manifest file
