### ISSUE TITLE
Lower minimum required Android API version

### ISSUE THREAD

**Issue by dvkch** [TelemetryDeck/KotlinSDK#8]
Hello!

I noticed the minimum Android API level required is 24. If possible, adding versions up to 22 or 21 would allow for around 9% more market share, according to Android Studio estimating API 24 reaching 89% of users and API 21 reaching 98%.

I'd gladly provide help to lower the requirements a bit if needed :) 

Thanks you for this beautiful project and for your time

**Comment by winsmith** [comment]
Hi, sounds like a smart idea. I think we use some APIs that need 24 if I remember correctly, but I'll see what I can do

**Comment by dvkch** [comment]
That would be amazing! I took a very quick look at the lib files and except for some minor things like updated method signatures for DateFormat and things like that I _think_ it should be okay. Maybe the LifecycleObserver could also have some changes between API versions.

**Comment by winsmith** [comment]
That would be amazing, thank you!
